name: CodeScan

on:
  push:
    branches: [ "📦Current" ]
  pull_request:
    branches: [ "📦Current" ]
  schedule:
    - cron: '32 7 * * 6'

permissions:
  contents: read

jobs:
  CodeScan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: windows-latest

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache files
        uses: actions/cache@v3
        with:
          path: |
            ~/.sonar
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run Analysis
        uses: codescan-io/codescan-scanner-action@5b2e8c5683ef6a5adc8fa3b7950bb07debccce12
        with:
          login: ${{ secrets.CODESCAN_AUTH_TOKEN }}
          organization: ${{ secrets.CODESCAN_ORGANIZATION_KEY }}
          projectKey: ${{ secrets.CODESCAN_PROJECT_KEY }}
          args: >
            -Dsonar.sources=.
            -Dsonar.scanAll=true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: codescan.sarif
